schema_version = "1.0.0"

id = "uv_tech_tools"
version = "0.35.1"
name = "TechArt Tools"
tagline = "Technical art tools for UV unwrapping, texel density and mesh QA"
maintainer = "Dzmitry Ivanou <id.cgtalk@gmail.com>"
type = "add-on"

tags = ["UV", "Mesh"]

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
