schema_version = "1.0.0"

id = "uv_tech_tools"
version = "0.1.0"
name = "UV Tech Tools"
tagline = "Tools for technical UV unwrapping workflows"
maintainer = "Dzmitry Ivanou <id.cgtalk@gmail.com>"
type = "add-on"

website = ""

tags = ["UV", "Mesh"]

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
